# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e485e49266a9b8ba0acd143726010960ee7c22a871701ea24187115ee89fa110c897a2d3f12aeb3778aad25bf95fc166fca105d71ec4525d361d4f538587fe9

test:
  secret_key_base: c9beb986b0223118c078399e25bab4d7f89e7a0333605e85900411f944c9aab7c612b7872ffc7d2662999ce43e01e4ce68a7874ac5420f8ee2c986af2c302953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
